# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 04:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beverage_name', models.CharField(max_length=2048, verbose_name='beer name')),
                ('beverage_abv', models.FloatField(verbose_name='alcohol by volume')),
            ],
        ),
        migrations.CreateModel(
            name='Beverage_Serving_Graphic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beverage_serving_graphic', models.ImageField(upload_to='theonly/beverage_serving_graphic/', verbose_name='serving graphic')),
            ],
        ),
        migrations.CreateModel(
            name='Beverage_Serving_Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beverage_serving_size', models.CharField(max_length=256, unique=True, verbose_name='serving size')),
            ],
        ),
        migrations.CreateModel(
            name='Beverage_Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beverage_style', models.CharField(max_length=256, unique=True, verbose_name='beverage style')),
            ],
        ),
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brewery_name', models.CharField(max_length=2048, unique=True, verbose_name='brewery name')),
            ],
        ),
        migrations.CreateModel(
            name='Brewery_Graphic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brewery_graphic', models.ImageField(upload_to='theonly/brewery_graphic/', verbose_name='brewery graphic')),
            ],
        ),
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tap_number', models.PositiveSmallIntegerField(unique=True)),
                ('beverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theonly.Beverage')),
                ('beverage_serving_graphic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theonly.Beverage_Serving_Graphic')),
                ('beverage_serving_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theonly.Beverage_Serving_Size', verbose_name='menu serving size')),
                ('brewery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theonly.Brewery')),
            ],
        ),
        migrations.AddField(
            model_name='brewery',
            name='brewery_graphic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theonly.Brewery_Graphic'),
        ),
        migrations.AddField(
            model_name='beverage',
            name='beverage_style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theonly.Beverage_Style'),
        ),
        migrations.AddField(
            model_name='beverage',
            name='brewery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theonly.Brewery', verbose_name='beverage brewery'),
        ),
    ]
