# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-08 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theonly', '0002_auto_20170403_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menumodel',
            options={'ordering': ['tap_number']},
        ),
        migrations.AddField(
            model_name='menumodel',
            name='menu_row',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
