# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-09 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theonly', '0004_auto_20170408_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menumodel',
            options={},
        ),
        migrations.AddField(
            model_name='menumodel',
            name='beverage_name',
            field=models.CharField(default='Rex', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menumodel',
            name='beverage_price_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='menumodel',
            name='beverage_price_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='menumodel',
            name='beverage_serving_graphic_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='serving_size_one', to='theonly.Beverage_Serving_Graphic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menumodel',
            name='beverage_serving_graphic_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='serving_size_two', to='theonly.Beverage_Serving_Graphic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menumodel',
            name='beverage_serving_size_1',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='menumodel',
            name='beverage_serving_size_2',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='menumodel',
            name='beverage_type',
            field=models.CharField(default='Cider', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menumodel',
            name='brewery_name',
            field=models.CharField(default='C', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menumodel',
            name='two_serving_sizes',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
