# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-09 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theonly', '0006_auto_20170409_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodel',
            name='beverage_serving_size_1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='menumodel',
            name='beverage_serving_size_2',
            field=models.CharField(max_length=255),
        ),
    ]
